name = "Hrizolight"
author = "P5ina"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c20ee4753c7da4a0253416101dab11666b2ce1531c453b47d95ac1a25fb75eb8"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
