name = "Hrizolight"
author = "P5ina"
version = "2.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96be2c99ff39a14e636b6acfd7dcf331cd73fe285329f0ac959d6c0bc0ad2f57"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
