name = "Hrizolight"
author = "P5ina"
version = "2.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f830ca5ab03b39a77b9149e30e1d5dbd3fe649bbbcba27996d01149132089dc"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
