name = "Hrizolight"
author = "P5ina"
version = "2.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7c1e39b147b8b23e8d0e76b7b91112480d270808f157b1e55d3d6e723fdcd58"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
