name = "Hrizolight"
author = "P5ina"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47b46b78cc11fab4be342f4996af90b48b87252d32ab5abefb52757cee104b22"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
